# Generated by Django 6.0.7 on 2026-07-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('care_type', models.CharField(choices=[('elderly', 'Elderly Care'), ('dementia', 'Dementia Care'), ('personal', 'Personal Care'), ('overnight', 'Overnight Care'), ('companionship', 'Companionship')], max_length=50)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carers.carer')),
            ],
        ),
    ]
