# Generated by Django 6.0.7 on 2026-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
