# Generated by Django 6.0.7 on 2026-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('experience_years', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bio', models.TextField()),
                ('dbs_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
