# Generated by Django 6.0.7 on 2026-07-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
    ]
