# Generated by Django 6.0.7 on 2026-07-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0002_carer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='carers/'),
        ),
    ]
