# Generated by Django 6.0.7 on 2026-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0003_carer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='care_type',
            field=models.CharField(choices=[('Dementia Care', 'Dementia Care'), ('Personal Care', 'Personal Care'), ('Companionship', 'Companionship'), ('Overnight Care', 'Overnight Care')], default='Personal Care', max_length=50),
        ),
    ]
