# Generated by Django 6.0.7 on 2026-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0004_carer_care_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('experience_years', models.PositiveIntegerField()),
                ('care_type', models.CharField(choices=[('Dementia Care', 'Dementia Care'), ('Personal Care', 'Personal Care'), ('Companionship', 'Companionship'), ('Overnight Care', 'Overnight Care')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
