# Generated by Django 6.0.7 on 2026-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0005_carerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='carerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
