# Generated by Django 6.0.7 on 2026-07-31 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0008_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=datetime.date(2026, 8, 1)),
            preserve_default=False,
        ),
    ]
