# Generated by Django 6.0.7 on 2026-08-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0009_remove_availability_day_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
