# Generated by Django 6.0.7 on 2026-08-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0010_availability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DBS', 'DBS'), ('First Aid', 'First Aid'), ('Qualification', 'Qualification'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='carer_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='carers.carer')),
            ],
        ),
    ]
