# Generated by Django 6.0.7 on 2026-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0011_carerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerdocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='carerdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
