# Generated by Django 6.0.7 on 2026-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0012_remove_carerdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
