# Generated by Django 6.0.7 on 2026-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0014_alter_carerdocument_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerdocument',
            name='document_name',
            field=models.CharField(blank=True, choices=[('DBS Certificate', 'DBS Certificate'), ('Right to Work', 'Right to Work'), ('Public Liability Insurance', 'Public Liability Insurance'), ('First Aid', 'First Aid'), ('Moving & Handling', 'Moving & Handling'), ('Safeguarding Adults', 'Safeguarding Adults'), ('Medication Administration', 'Medication Administration'), ('Dementia Awareness', 'Dementia Awareness'), ('Infection Control', 'Infection Control'), ('Autism Awareness', 'Autism Awareness'), ('Care Certificate', 'Care Certificate'), ('NVQ Level 2', 'NVQ Level 2'), ('NVQ Level 3', 'NVQ Level 3')], max_length=200, null=True),
        ),
    ]
