# Generated by Django 6.0.7 on 2026-08-02 14:41

import carers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0015_alter_carerdocument_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='carerdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carerdocument',
            name='file',
            field=models.FileField(upload_to=carers.models.document_upload_path),
        ),
    ]
