# Generated by Django 6.0.7 on 2026-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0016_carer_address_carer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
