# Generated by Django 6.0.7 on 2026-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0017_carer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='services_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='carer',
            name='care_type',
            field=models.CharField(choices=[('Personal Care', 'Personal Care'), ('Dementia Care', 'Dementia Care'), ('Companionship', 'Companionship'), ('Overnight Care', 'Overnight Care'), ('Respite Care', 'Respite Care'), ('Learning Disabilities Support', 'Learning Disabilities Support'), ('Autism Support', 'Autism Support'), ('Live-in Care', 'Live-in Care'), ('Mobility Support', 'Mobility Support'), ('Domestic Support', 'Domestic Support'), ('Shopping & Community Access', 'Shopping & Community Access')], default='Personal Care', max_length=50),
        ),
        migrations.AlterField(
            model_name='carerapplication',
            name='care_type',
            field=models.CharField(choices=[('Personal Care', 'Personal Care'), ('Dementia Care', 'Dementia Care'), ('Companionship', 'Companionship'), ('Overnight Care', 'Overnight Care'), ('Respite Care', 'Respite Care'), ('Learning Disabilities Support', 'Learning Disabilities Support'), ('Autism Support', 'Autism Support'), ('Live-in Care', 'Live-in Care'), ('Mobility Support', 'Mobility Support'), ('Domestic Support', 'Domestic Support'), ('Shopping & Community Access', 'Shopping & Community Access')], max_length=50),
        ),
    ]
